languageCode = "en-au"
baseurl = "http://www.patrickyates.me/"
builddrafts = false
canonifyurls = false
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
author = "Patrick Yates"
title = "Patrick Yates"
pygmentsuseclasses = true
pluralizelisttitles = false
theme = "cocoa"

#disqusshortname = "cocoaexamplesite" # Comment out to disable Disqus.


[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = "Patrick Yates"
# gravatar = "7db078143f5c14085123d780ea92458e" # do not use in the same time as Avatar
avatar = "img/me.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as Gravatar)
# cachebuster = false # FIXME: See issue #32.
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Personal blog for Patrick Yates"
email = "mail@patrickyates.me"
faviconfile = "img/orange.png"
gatracker = "XYZ"
github = "//github.com/opcon"
highlightjs = true
# highlightjslanguages = ["go"] # additional languages not included in the "common" set
initials = "py" # Displayed on single post page; DEPRECATED in v0.3.0.
lang = "en"
linkedin = "//linkedin.com/in/patrick-yates"
twitter = "//twitter.com/opcon_gamedev"

extracssfiles = [ "/css/override.css" ] # In your `static/css`, add/remove files as necessary.
